---
name: pkg_sample
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  injectable: 2.5.2
  get_it: 8.2.0
  path_provider: 2.1.5

dev_dependencies:
  build_runner: 2.10.1
  injectable_generator: 2.9.0

flutter:
  uses-material-design: true
