---
name: pkg_sample
publish_to: none
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  injectable: 2.5.0
  get_it: 8.0.3
  path_provider: 2.1.5

dev_dependencies:
  build_runner: 2.4.14
  injectable_generator: 2.7.0

flutter:
  uses-material-design: true
