name: skeleton

packages:
  - packages/**

command:
  bootstrap:
    hooks:
      post: |
        melos exec -c 1 -- flutter pub get
    description: Bootstrap all packages

  clean:
    hooks:
      post: melos exec -- flutter clean
    description: Clean all packages

scripts:
  get:
    run: |
      melos exec -c 1 -- flutter pub get
    description: Run 'packages get' in all packages.

  analyze:
    run: melos exec -c 1 -- flutter analyze
    description: Analyze all packages

  gen:
    run: |
      melos exec -- dart run build_runner build --delete-conflicting-outputs
    description: Regenerate code using build_runner package.
    packageFilters:
      dependsOn: "build_runner"

  slang:
    run: |
      melos exec -c 1 -- dart run slang
    description: Generate translations using slang package.
    packageFilters:
      dependsOn: "slang"
