name: skeleton

version: 0.0.0+1
publish_to: "none"

environment:
  sdk: ^3.9.0
  flutter: "3.35.0"

workspace:
  - packages/pkg_common_api
  - packages/pkg_common_ui
  - packages/pkg_localizations
  - packages/pkg_user

dependencies:
  flutter:
    sdk: flutter

  # sl
  injectable: 2.5.2
  get_it: 8.2.0

  # l10n
  slang: 4.9.2
  slang_flutter: 4.9.0

  # db
  hive_ce: 2.15.1

  # state management
  flutter_bloc: 9.1.1

  # utils
  equatable: 2.0.7
  fpdart: 1.2.0
  loggy: 2.0.3
  auto_route: 10.2.0
  path_provider: 2.1.5
  rxdart: 0.28.0
  formz: 0.8.0
  melos: 7.3.0

  # ui
  flutter_svg: 2.2.1

  # packages
  pkg_common_api:
    path: packages/pkg_common_api
  pkg_common_ui:
    path: packages/pkg_common_ui
  pkg_user:
    path: packages/pkg_user

dev_dependencies:
  flutter_test:
    sdk: flutter

  # generators
  injectable_generator: 2.9.0
  build_runner: 2.10.1
  auto_route_generator: 10.2.5
  slang_build_runner: 4.9.0

  # metrics
  lint: 2.8.0

flutter:
  uses-material-design: true
  assets:
    - packages/pkg_common_ui/assets/fonts/
    - packages/pkg_common_ui/assets/icons/navigation/

  fonts:
    - family: Poppins
      fonts:
        - asset: packages/pkg_common_ui/assets/fonts/poppins-semibold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: packages/pkg_common_ui/assets/fonts/inter-bold.ttf
          weight: 700
        - asset: packages/pkg_common_ui/assets/fonts/inter-semibold.ttf
          weight: 600
        - asset: packages/pkg_common_ui/assets/fonts/inter-medium.ttf
          weight: 500
        - asset: packages/pkg_common_ui/assets/fonts/inter-regular.ttf
          weight: 400

melos:
  scripts:
    get:
      run: |
        melos exec -c 1 -- flutter pub get
      description: Run 'packages get' in all packages.

    analyze:
      run: melos exec -c 1 -- flutter analyze
      description: Analyze all packages

    gen:
      run: |
        melos exec -c 1 -- dart run build_runner build --delete-conflicting-outputs
      description: Regenerate code using build_runner package.
      packageFilters:
        dependsOn: "build_runner"

    slang:
      run: |
        melos exec -c 1 -- dart run slang
      description: Generate translations using slang package.
      packageFilters:
        dependsOn: "slang"