---
name: pkg_common_api
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  injectable: 2.5.2
  get_it: 8.2.0
  path_provider: 2.1.5
  hive_ce: 2.15.1
  equatable: 2.0.7
  fpdart: 1.2.0
  loggy: 2.0.3

dev_dependencies:
  build_runner: 2.10.1
  injectable_generator: 2.9.0

flutter:
  uses-material-design: true
