---
name: pkg_localizations
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  slang: 4.9.2

dev_dependencies:
  build_runner: 2.10.1
  slang_build_runner: 4.9.0

flutter:
  uses-material-design: true
