---
name: pkg_localizations
publish_to: none
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  slang: 4.4.1

dev_dependencies:
  build_runner: 2.4.14
  slang_build_runner: 4.4.2

flutter:
  uses-material-design: true
