---
name: pkg_common_ui
publish_to: none
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.17

dev_dependencies:
  build_runner: 2.4.14

flutter:
  uses-material-design: true
