---
name: pkg_common_ui
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.2.1
  pkg_localizations:
    path: packages/pkg_localizations

flutter:
  uses-material-design: true
