name: on push action

on:
  push:

jobs:
  validate_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter --version
      - run: flutter pub global activate melos
      - run: flutter pub global run melos bootstrap
      - run: flutter pub global run melos run get -- \
      - run: flutter pub global run melos run analyze -- \
