---
name: pkg_user
publish_to: none
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  injectable: 2.5.0
  get_it: 8.0.3
  path_provider: 2.1.5
  fpdart: 1.1.1
  equatable: 2.0.7
  loggy: 2.0.3

  pkg_common_api:
    path: ../pkg_common_api

dev_dependencies:
  build_runner: 2.4.14
  injectable_generator: 2.7.0

flutter:
  uses-material-design: true
